# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 #checkout 代码

      - name: Setup provisioning profile
        run: |
          exec .github/scripts/set-env-from-xcodeproj.sh
      - uses: yukiarrr/ios-build-action@v1.3.0
        with:
            project-path: ActionsTest.xcodeproj
#            workspace-path: ActionsTest.xcworkspace # optional
            certificate-password: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}
            p12-base64: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
            mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
            code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
            team-id: ${{ secrets.TEAM_ID }}
            export-method: 'development'
#      - name: Import signing certificate
#        env:
#          SIGNING_CERTIFICATE_P12_DATA: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
#          SIGNING_CERTIFICATE_PASSWORD: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}
#        run: |
#          exec .github/scripts/import-certificate.sh
#
#      - name: Import provisioning profile
#        env:
#          PROVISIONING_PROFILE_DATA: ${{ secrets.PROVISIONING_PROFILE_DATA }}
#        run: |
#          exec .github/scripts/import-profile.sh

#      - name: Archiving project
#        run: ./.github/scripts/archive_app.sh
#
#      - name: Exporting ipa
#        run: ./.github/scripts/export_ipa.sh
